# Generated by Django 5.1.6 on 2025-03-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_delete_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EnrollmentDate',
            field=models.DateField(),
        ),
    ]
